### PR TITLE
fix: outdated `caniuse-lite`

### LINKED ISSUE #2165: `Browserslist: caniuse-lite is outdated.`

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #2165.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
@crimx what are your thoughts on this pull request?

**Review by crimx — APPROVED** [review]

**Comment by crimx** [comment]
Hi thanks for the PR. I am working on updating the entire stack too.

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
> Hi thanks for the PR. I am working on updating the entire stack too.

Should I hold off on proposing any other changes because of this?

**Pull request merged**
